import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import ReduxProvider from "./redux/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <ReduxProvider>
            <Header/>
            {children}
            <Footer/>
          </ReduxProvider>
        </body>
    </html>
  );
}
